name: PBC Service Staging Deployment

on:
    push:
        branches:
            - develop
            - features/added-workflow
    workflow_dispatch:
        inputs:
            deploy:
                description: Enter 'staging' to deploy to staging
                required: true
                default: "no"

jobs:
    deploy-to-staging:
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'staging')
        name: Deploy to Staging
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

#            -   name: 📂 Sync files
#                uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#                with:
#                    server: ${{ secrets.ftp_host }}
#                    username: ${{ secrets.ftp_username }}
#                    password: ${{ secrets.ftp_password }}
#                    server-dir: staging.pbcservice.com/pbcs/
#                    exclude: |
#                        **/.git*
#                        **/.git*/**
#                        .gitattributes
#                        release.sh
#                        Readme.md

            -   name: Execute remote SSH commands using password
                uses: appleboy/ssh-action@v1
                with:
                    host: ${{ secrets.ssh_host }}
                    username: ${{ secrets.ssh_username }}
                    password: ${{ secrets.ssh_password }}
#                    port: ${{ secrets.ssh_port }}
                    script: |
                        echo "------------------------------"
                        echo "I am started"
                        pwd
                        whoami
                        ls -al
                        echo "I am ended"
                        echo "------------------------------"
